name: ROS Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, copyright, lint_cmake]
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.6
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: humble
        linter: ${{ matrix.linter }}
        package-name:
          sr_moveit2_utils
          sr_manipulation_interfaces


  ament_lint_100:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cpplint]
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.6
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: humble
        linter: cpplint
        arguments: "--linelength=100 --filter=-whitespace/newline"
        package-name:
          sr_moveit2_utils
          sr_manipulation_interfaces
          sr_manipulation
